name: HomeGenie
baseurl: '/HomeGenie'
markdown: kramdown
highlighter: rouge
collections:
  docs:
    output: true
prose:
  rooturl: ''
  media: 'images/docs'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes

